from .zh_prompt import TEXT_PREPROCESSING_PROMPT as ZH_TEXT_PREPROCESSING_PROMPT
from .en_prompt import TEXT_PREPROCESSING_PROMPT as EN_TEXT_PREPROCESSING_PROMPT

# 用字典方式組織，方便按語言選擇
TEXT_PREPROCESSING_PROMPTS = {
    "zh": ZH_TEXT_PREPROCESSING_PROMPT,
    "en": EN_TEXT_PREPROCESSING_PROMPT
}